/*
  Copyright 2022 Loophole Labs

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

// Code generated by protoc-gen-ts-polyglot 0.2.0. DO NOT EDIT.
import { encodeString, decodeString, encodeInt64, decodeInt64, encodeUint8Array, decodeUint8Array, encodeInt32, decodeInt32, encodeMap, Kind, decodeMap, encodeArray, decodeArray } from "@loopholelabs/polyglot-ts";

import { StringList } from "./http.signature";

export class Response {
  constructor(StatusCode: number, Body: Uint8Array, Headers: Map<string, StringList>) {
    this._StatusCode = StatusCode
    this._Body = Body
    this._Headers = Headers
  }

  private _StatusCode: number;

  get StatusCode(): number {
    return this._StatusCode
  }

  set StatusCode(StatusCode: number) {
    this._StatusCode = StatusCode
  }

  private _Body: Uint8Array;

  get Body(): Uint8Array {
    return this._Body
  }

  set Body(Body: Uint8Array) {
    this._Body = Body
  }

  private _Headers: Map<string, StringList>;

  get Headers(): Map<string, StringList> {
    return this._Headers
  }

  set Headers(Headers: Map<string, StringList>) {
    this._Headers = Headers
  }

  encode(buf: Uint8Array): Uint8Array {
    let encoded = buf
    encoded = encodeInt32(encoded, this._StatusCode)
    encoded = encodeUint8Array(encoded, this._Body)
    encoded = encodeMap(encoded, this._Headers.size,
      Kind.String, Kind.Any)
    this._Headers.forEach((value, key) => {
      encoded = encodeString(encoded, key);
      encoded = value.encode(encoded);
    })
    return encoded
  }

  static decode(buf: Uint8Array): {
    buf: Uint8Array,
    value: Response
  } {
    let decoded = buf
    const StatusCode = decodeInt32(decoded)
    decoded = StatusCode.buf
    const Body = decodeUint8Array(decoded)
    decoded = Body.buf
    const HeadersMap = decodeMap(decoded)
    decoded = HeadersMap.buf
    const Headers: { value: Map<string, StringList> } = {
      value: new Map<string, StringList>(),
    }

    for (let i = 0; i < HeadersMap.size; i++) {
      const key = decodeString(decoded);
      decoded = key.buf;
      const value = StringList.decode(decoded);
      decoded = value.buf;
      Headers.value.set(key.value, value.value);
    }

    return {
      buf: decoded,
      value: new Response(StatusCode.value, Body.value, Headers.value)
    }
  }
}
