name: Rust

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run fmt
        run: cargo fmt --all -- --check
      - name: Build
        run: cargo build --verbose --release
      - name: Publish to crates.io
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: cargo publish --token $CRATES_IO_TOKEN
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
